### ISSUE TITLE
Pulling or pushing nonexisting files fails

### ISSUE THREAD

**Issue by mikkpr** [Voog/kit-cli#5]
`voog push foobar` doesn't give a meaningful error message:

```
Pulling files from zurich-dev-com (zurich-dev.voog.computer)
Error: Promise rejected with value: undefined
    at /usr/local/lib/node_modules/voog-kit/node_modules/loud-rejection/index.js:27:12
    at Array.forEach (native)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/voog-kit/node_modules/loud-rejection/index.js:23:24)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
    at emit (/usr/local/lib/node_modules/voog-kit/node_modules/signal-exit/index.js:68:11)
    at processEmit [as emit] (/usr/local/lib/node_modules/voog-kit/node_modules/signal-exit/index.js:141:5)
```

**Comment by mikkpr** [comment]
Also `voog push` on its own fails:

```
fs.js:945
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.listFolders (/usr/local/lib/node_modules/voog-kit/node_modules/kit-core/index.js:66:13)
    at filesFor (/usr/local/lib/node_modules/voog-kit/node_modules/kit-core/index.js:297:24)
    at Object.totalFilesFor (/usr/local/lib/node_modules/voog-kit/node_modules/kit-core/index.js:286:15)
    at pushAllFiles (/usr/local/lib/node_modules/voog-kit/index.js:154:37)
    at Object.push (/usr/local/lib/node_modules/voog-kit/index.js:181:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/voog-kit/index.js:361:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
```
