### ISSUE TITLE
"voog pull" fails randomly.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/kit-cli#7]
I executed **"voog pull"** twice.

First output:

```
Pulling files from live (lahhentagge.voog.com)
Pulling |======================  | 93% page-header-bg_huge.jpgError: getaddrinfo ENOTFOUND lahhentagge.voog.com lahhentagge.voog.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

Second time (~10 seconds later):

```
Pulling files from live (lahhentagge.voog.com)
Pulling |========================| 100% Successfully pulled 100 files
```

I don't know, maybe it had something to do with my connection but just in case I will report it here. :)

**Comment by kaspar-naaber** [comment]
And another site with differend error:

First output:

```
Pulling files from live (maarjanuut.com)
/usr/local/lib/node_modules/voog-kit/node_modules/kit-core/index.js:526
      var ret = data.filter(function (l) {
                     ^

TypeError: data.filter is not a function
    at /usr/local/lib/node_modules/voog-kit/node_modules/kit-core/index.js:526:22
    at Request._callback (/usr/local/lib/node_modules/voog-kit/node_modules/voog/lib/client.js:28:58)
    at Request.self.callback (/usr/local/lib/node_modules/voog-kit/node_modules/voog/node_modules/request/request.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/voog-kit/node_modules/voog/node_modules/request/request.js:1019:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/voog-kit/node_modules/voog/node_modules/request/request.js:970:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Second output (also ~10 seconds later).

```
maarjanuut(master) ✗: voog pull
Pulling files from live (maarjanuut.com)
Pulling |========================| 100% Successfully pulled 153 files
```

**Comment by kaspar-naaber** [comment]
Pulling specific folders also fails.

```
lahhentagge(master): voog pull layouts/
Pulling files from live (lahhentagge.voog.com)
Error: Promise rejected with value: undefined
    at /usr/local/lib/node_modules/voog-kit/node_modules/loud-rejection/index.js:27:12
    at Array.forEach (native)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/voog-kit/node_modules/loud-rejection/index.js:23:24)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
    at emit (/usr/local/lib/node_modules/voog-kit/node_modules/signal-exit/index.js:68:11)
    at processEmit [as emit] (/usr/local/lib/node_modules/voog-kit/node_modules/signal-exit/index.js:141:5)
```
